### ISSUE TITLE
Show file path, as normal tab

### ISSUE THREAD

**Issue by linonetwo** [billgoo/vscode-tab-group#18]
So two index.ts won't confuse with each other.

![截屏2023-02-02 22 55 50](https://user-images.githubusercontent.com/3746270/216358830-c53bf629-2753-419d-a468-44a173d4dc27.png)
![截屏2023-02-02 22 55 59](https://user-images.githubusercontent.com/3746270/216358843-7b47d3ab-ef61-42e6-afac-2ac1a22ee5ee.png)

**Comment by Nesvet** [comment]
@billgoo, pal, are you here?

**Comment by billgoo** [comment]
> @billgoo, pal, are you here?

@Nesvet Sorry for the late reply. Busy with some personal thing and not able to update all these discussion in time. Will work on them once I have time. You could also submit pull request to this repo.
Thank you for your patient and understanding.
